ktor {
    profile = "development"
    development = true

    deployment {
        port = 8080
        adminPort = 8090
    }

    application {
        modules = [ com.sap.pi.analysis.ApplicationKt.main ]
    }
}

jwt {
    signingKey = "test123asdf1!"
}

pi {
    environment = staging_cloud_os_eu
}